"""Generate the frontend runtime configuration.

frontend/js/config.js is intentionally not committed because its API endpoint
depends on the selected runtime environment.
"""

from pathlib import Path
import json
import sys

PROJECT_ROOT = Path(__file__).resolve().parent.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config.env_settings import settings


def main() -> None:
    output_path = PROJECT_ROOT / "frontend" / "js" / "config.js"

    config = {
        "API_BASE_URL": settings.API_BASE_URL,
    }

    content = (
        "// Auto-generated by scripts/gen_frontend_config.py\n"
        "// Do not edit manually.\n"
        f"window.APP_CONFIG = {json.dumps(config, ensure_ascii=False)};\n"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    print(f"Generated frontend config: {output_path}")
    print(f"API_BASE_URL={settings.API_BASE_URL}")


if __name__ == "__main__":
    main()
